# Enable C++ support
language: cpp

cache:
    directories:
      - /home/travis/build/CosmoStat/Glimpse/build/SPARSE2D
      - /home/travis/build/CosmoStat/Glimpse/build/NICAEA

os:
  - linux
  - osx
  
# Compiler selection
compiler:
    - gcc


install:
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew cask uninstall oclint; fi
    - if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then brew install gsl fftw nfft armadillo boost ccfits; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install -qq cmake libgsl0-dev libfftw3-3 libccfits-dev libnfft3-dev libarmadillo-dev libboost-all-dev; fi

#- sudo apt-get install -qq nvidia-cuda-dev

# Build steps
script:
    - mkdir -p build && cd build
    - cmake ..
    - make
    - ./glimpse --version
