# Enable C++ support
language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      name: linux
    - os: osx
      osx_image: xcode11.3
      name: OSX

addons:
  apt:
    packages:
      - cmake
      - libgsl0-dev
      - libfftw3-3
      - libccfits-dev
      - libnfft3-dev
      - libarmadillo-dev
      - libboost-all-dev
  homebrew:
    taps: brewsci/science
    packages:
      - gcc
      - cmake
      - nfft
      - gsl
      - fftw
      - ccfits
      - armadillo
      - boost

cache:
    directories:
      - /home/travis/build/CosmoStat/Glimpse/build/SPARSE2D
      - /home/travis/build/CosmoStat/Glimpse/build/NICAEA

# Compiler selection
compiler:
    - gcc

sudo: required

before_install:
  - |
    if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      eval "CC=gcc-9 && CXX=g++-9"
    fi


install: true

# Build steps
script:
    - mkdir -p build && cd build
    - cmake ..
    - make
    - ./glimpse --version
