# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq cmake libgsl0-dev libfftw3-3  libccfits-dev libnfft3-dev libarmadillo-dev

install: true

# Build steps
script:
  - mkdir build && cd build
  - cmake ..
  - make
